apiVersion: apps/v1
kind: Deployment
metadata:
    name: employees-deploy
    labels:
        name: employees-deploy
        app: em
spec:
    replicas: 3
    selector:
        matchLabels:
          name: emp-pod
          app: em
    template:
      metadata:
          name: emp-pod
          labels:
              name: emp-pod
              app: em
      spec:
          containers:
              - name: employee-app
                image: rnozdrachev/emp-project:1.1.1
                ports:
                    - containerPort: 8761