apiVersion: v1
kind: Service
metadata:
    name: emp-service
    labels:
        name: emp-service
        app: em
spec:
    type: NodePort
    ports:
        - port: 8761
          targetPort: 8761
          nodePort: 30007
    selector:
        name: emp-pod
        app: em