---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    ap: postgres
    app: em
data:
  POSTGRES_DB: emps
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: Roman1995!
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 1Gi
  hostPath:
    path: /ttp/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deploy
    labels:
        name: postgres-deploy
        app: em
        ap: postgres
spec:
    replicas: 2
    selector:
        matchLabels:
          name: postgres-pod
          app: em
          ap: postgres
    template:
      metadata:
          name: postgres-pod
          labels:
              name: postgres-pod
              app: em
              ap: postgres
      spec:
          containers:
              - name: postgres
                image: postgres:14.2
                imagePullPolicy: "IfNotPresent"
                ports:
                    - containerPort: 5432
                envFrom:
                    - configMapRef:
                        name: postgres-config
                volumeMounts:
                    - mountPath: /var/lib/postgresql/data
                      name: data-volume1
          volumes:
               - name: data-volume1
                 persistentVolumeClaim:
                   claimName: claim-volume
# ---
# apiVersion: v1
# kind: Pod
# metadata:
#     name: postgres-pod
#     labels:
#         name: postgres-pod
#         app: em
#         ap: postgres
# spec:
#    containers:
#      - name: postgres
#        image: postgres:14.2
#        imagePullPolicy: "IfNotPresent"
#        ports:
#            - containerPort: 5432
#        envFrom:
#            - configMapRef:
#                name: postgres-config
#        volumeMounts:
#            - mountPath: /var/lib/postgresql/data
#              name: data-volume
#    volumes:
#         - name: data-volume
#           hostPath:
#             path: /data
#             type: Directory
---
apiVersion: v1
kind: Service
metadata:
    name: db
    labels:
        name: postgres-service
        app: em
        ap: postgres
spec:
    ports:
        - port: 5432
          targetPort: 5432
    selector:
        name: postgres-pod
        app: em
        ap: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: employees-deploy
    labels:
        name: employees-deploy
        app: em
spec:
    replicas: 3
    selector:
        matchLabels:
          name: emp-pod
          app: em
    template:
      metadata:
          name: emp-pod
          labels:
              name: emp-pod
              app: em
      spec:
          containers:
              - name: employee-app
                image: rnozdrachev/emp-project:1.1.1
                ports:
                    - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
    name: emp-service
    labels:
        name: emp-service
        app: em
spec:
    type: NodePort
    ports:
        - port: 8761
          targetPort: 8761
          nodePort: 30007
    selector:
        name: emp-pod
        app: em