apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deploy
    labels:
        name: postgres-deploy
        app: em
spec:
    replicas: 2
    selector:
        matchLabels:
          name: postgres-pod
          app: em
    template:
      metadata:
          name: postgres-pod
          labels:
              name: postgres-pod
              app: em
      spec:
          containers:
              - name: postgres
                image: postgres:14.2
                ports:
                    - containerPort: 5432
                env:
                    - name: POSTGRES_USER
                      value: "postgres"
                    - name: POSTGRES_PASSWORD
                      value: "Roman1995!"
                    - name: POSTGRES_DB
                      value: "emps"
                    - name: POSTGRES_HOST_AUTH_METHOD
                      value: trust